# Generated by Django 2.1.4 on 2019-01-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0002_auto_20190104_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, default='0', help_text='Amount', max_digits=1000),
        ),
    ]
