# Generated by Django 2.1.4 on 2019-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0003_auto_20190104_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('Pending', 'PENDING'), ('Failed', 'FAILED'), ('Success', 'SUCCESS')], default='https://rinkeby.etherscan.io/tx/', help_text='Network link', max_length=150)),
                ('min_withdraw_amount', models.DecimalField(decimal_places=18, default='0', help_text='Minimal withdraw amount', max_digits=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hloruser',
            options={'verbose_name': 'User of Hlor', 'verbose_name_plural': 'Users of Hlor'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(help_text='Transaction hash', max_length=150),
        ),
    ]
