# Generated by Django 2.1.5 on 2019-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0005_auto_20190106_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='network_name',
            field=models.CharField(choices=[('mainnet', 'MAINNET'), ('rinkeby', 'RINKEBY')], default='rinkeby', help_text='Network name', max_length=150),
        ),
    ]
