# Generated by Django 2.1.5 on 2019-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0007_auto_20190108_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Wallet address', max_length=255),
        ),
    ]
